---
title: "Final Project"
author: "Muxuan Lyu"
date: "May 25, 2018"
output: 
  html_document:
    toc: true
    toc_float: true
toc_depth: 12
number_sections: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

# load packages
```{r, include=FALSE}
#load packages
library(tidyverse)
library(dotwhisker)
library(broom)
library(sjPlot) #reg table
library(ggcorrplot) #heatmap
library(plotly)
```


# get the data
```{r, include=FALSE}
#get the data
scale_by_type <- read_csv("ScaleByType.csv") #for regression dotwhisker plot by scene type
scale_all <- read_csv("scale2gather_final.csv") #for cor heat map and avg ratings plot
semantics <- read_csv("semantics.csv") #for semantic features

```


# data aggregation
```{r overall plot data aggregation}
#turing trees into binary 
semantics <- semantics %>%
  mutate(tree2 = ifelse(tree!=0, 1, 0))

#extract avg ratings
data_ratings <- scale_all[,c("time","type", "scene_type","AvePref")]

#extract semantics features
data_features <- semantics[1:1428, c("billboard","tree2","lake","house","sign")]

#combine datasets
ratings_features <- cbind(data_ratings, data_features)
#changing names of the levels
ratings_features$type = as.factor(ratings_features$type)
levels(ratings_features$type) = c("Flat 1", "Flat 2", "Hill 1", "Hill 2", "Mountain 1", "Mountain 2")


#assigning features
features_plot <- ratings_features %>%
  mutate(feature_type = ifelse(tree2 == 1 & billboard == 0 & lake == 0, "Tree", 
                           ifelse(tree2 == 0 & billboard == 1, "Billboard",
                                  ifelse(tree2 == 0 & lake == 1, "Lake",
                                        ifelse(tree2 == 1 & billboard == 1, "Billboard + Tree",
                                              ifelse(tree2 == 1 & lake == 1, "Lake + Tree",
                                                    ifelse(house == 1 & sign == 0, "House",
                                                          ifelse(sign == 1 & house == 0, "Traffic Sign",
                                                                ifelse(house == 1 & sign == 1, "House + Traffic Sign",
                                                                      "None"
                                                                      )))))))))

```


# overall plot
```{r overall plot}

g <- ggplot(features_plot, aes(time, AvePref, fill = feature_type)) +
    geom_col() +
    facet_wrap( ~ type, scale = "free_x", nrow = 1) + 
    #geom_line(aes(time, AvePref, group = type)) + #this line for ggplot only
    theme_bw() +
    theme(legend.position="bottom",
         strip.background =element_rect(fill="white")) +
    #assign diff colors to each features
    scale_fill_manual(values=c("darksalmon","goldenrod", 
                               "tan1", "tomato",
                              "skyblue", "dodgerblue",
                               "gainsboro",
                               "firebrick1",
                               "palegreen2"
                              )) +
     labs(title = "Average ratings under the influences of different features", 
        y = "Average rating (z-scored)",
        x = "Time (s)") +
     scale_x_continuous(breaks = seq(0, 120, by = 20), minor_breaks = seq(0, 120, 5)) +
     guides(fill=guide_legend(title="Features type")) 

#g
#ggsave("ratings_features_col.png")
ggplotly(g)  
```

# correlation heatmap
```{r cor heatmap}
features_cor <- scale_all %>%
  select(-type, -scene_type, -time, -sky, -slope, -AvePref)

corr_features <- round(cor(features_cor), 1)
p.mat <- cor_pmat(corr_features)
```

```{r}
ggcorrplot(corr_features, hc.order = TRUE, outline.col = "white", type = "upper", lab = TRUE) +
  labs(title = "Correlations between low-level viusal and semantic features")
```

# reg tables
```{r regression models build-up}
#regression analysis by scene type
flat_reg <- scale_by_type[1:480,]
hill_reg <- scale_by_type[481:960,]
mount_reg <- scale_by_type[961:1428,]

#build regression models by scene type
fit_flat = lm(AvePref ~ Edge + Hue + Sat + Lum + sdHue + sdSat + sdBright + Entropy + 
                tree_PC1 + sign + house + billboard,
          data = flat_reg)

fit_hill = lm(AvePref ~ Edge + Hue + Sat + Lum + sdHue + sdSat + sdBright + Entropy + 
                tree_PC1 + sign + lake,
          data = hill_reg)

fit_mount = lm(AvePref ~ Edge + Hue + Sat + Lum + sdHue + sdSat + sdBright + Entropy + 
                tree_PC1 + lake,
          data = mount_reg)
```


##### Visualize regression table 1
```{r dotwhisker plot 1}

two_brackets <- list(c("Low-Level Visual Features","Edge", "Entropy"), 
                       c("Semantic Features","*Tree", "***Billboard")
                      )

{dwplot(fit_flat, dot_args = list(size = .5, color = "firebrick3")) %>%
  relabel_predictors(c(Edge = "Edge", 
                       Hue = "**Hue",
                       Sat = "Saturation",
                      Lum = "***Brightness",
                      sdHue = "*SD Hue",
                      sdSat = "***SD Saturation",
                      sdBright = "**SD Brightness",
                       Entropy = "Entropy",
                      tree_PC1 = "*Tree",
                      sign = "Traffic Sign",
                      house = "House",
                      billboard = "***Billboard")) +
  theme_bw() + xlab("Coefficient Estimate") + ylab("") +
  geom_vline(xintercept = 0, colour = "grey40", linetype = 2) +
  ggtitle("Predicting Preference Ratings in Flat Terrains") +
  theme(legend.position="none",
       plot.title = element_text(face = "bold"),
       axis.text.y=element_text(size=rel(1.1)))} %>% 
  add_brackets(two_brackets)



```


##### Visualize regression table 2
```{r dotwhisker plot 2}
two_brackets <- list(c("Low-Level Visual Features","Edge", "***Entropy"), 
                       c("Semantic Features","***Tree", "***Lake")
                      )

{dwplot(fit_hill, dot_args = list(size = .5, color = "firebrick3")) %>%
  relabel_predictors(c(Edge = "Edge", 
                       Hue = "Hue",
                       Sat = "***Saturation",
                      Lum = "***Brightness",
                      sdHue = "SD Hue",
                      sdSat = "***SD Saturation",
                      sdBright = "***SD Brightness",
                       Entropy = "***Entropy",
                      tree_PC1 = "***Tree",
                      sign = "Traffic Sign",
                      lake = "***Lake")) +
  theme_bw() + xlab("Coefficient Estimate") + ylab("") +
  geom_vline(xintercept = 0, colour = "grey40", linetype = 2) +
  ggtitle("Predicting Preference Ratings in Rolling Hills") +
  theme(legend.position="none",
        plot.title = element_text(face = "bold"),
        axis.text.y=element_text(size=rel(1.1)))} %>% 
  add_brackets(two_brackets)
```

##### Visualize regression table 3
```{r dot whiskerplot 3}
two_brackets <- list(c("Low-Level Visual Features","Edge", "Entropy"), 
                       c("Semantics","***Tree", "***Lake")
                      )

{dwplot(fit_mount, dot_args = list(size = .5, color = "firebrick3")) %>%
  relabel_predictors(c(Edge = "Edge", 
                       Hue = "***Hue",
                       Sat = "Saturation",
                      Lum = "**Brightness",
                      sdHue = "***SD Hue",
                      sdSat = "SD Saturation",
                      sdBright = "SD Brightness",
                      Entropy = "Entropy",
                      tree_PC1 = "***Tree",
                      lake = "***Lake")) +
  theme_bw() + xlab("Coefficient Estimate") + ylab("") +
  geom_vline(xintercept = 0, colour = "grey40", linetype = 2) +
  ggtitle("Predicting Preference Ratings in Mountainous Forests") +
  theme(legend.position="none",
        plot.title = element_text(face = "bold"),
        axis.text.y=element_text(size=rel(1.1)))} %>% 
  add_brackets(two_brackets)
```



